import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";

const [inputPath, outputPath, archiveDate = "2026-08-27"] = process.argv.slice(2);
if (!inputPath || !outputPath) {
  throw new Error(
    "usage: node export_schema_from_workbook.mjs <input.xlsx> <output.json> [archive-date]",
  );
}

const sourceBytes = await fs.readFile(inputPath);
const sourceSha256 = crypto.createHash("sha256").update(sourceBytes).digest("hex");
const workbook = await SpreadsheetFile.importXlsx(await FileBlob.load(inputPath));
const sheetName = "04_Schema";
const sourceRange = "A1:D66";
const rows = workbook.worksheets.getItem(sheetName).getRange(sourceRange).values;

const title = String(rows[0][0] ?? "");
const versionMatch = title.match(/semantic schema calibrated (v[0-9.]+)/i);
if (!versionMatch) {
  throw new Error(`cannot parse schema version from ${JSON.stringify(title)}`);
}
const schemaVersion = `semantic-schema-calibrated-${versionMatch[1]}`;
const headerIndex = rows.findIndex(
  (row) => row[0] === "Field" && row[1] === "Label/Rule",
);
if (headerIndex < 0) {
  throw new Error("04_Schema header not found");
}

const enumRows = [];
const dependencyRows = [];
for (const row of rows.slice(headerIndex + 1)) {
  const [field, label, definition, type] = row;
  if (!field && !label && !definition && !type) continue;
  if (type === "ENUM") {
    enumRows.push({ field, label, definition });
  } else if (type === "RULE" && field === "DEPENDENCY") {
    dependencyRows.push({ name: label, definition });
  } else {
    throw new Error(`unexpected schema row: ${JSON.stringify(row)}`);
  }
}

const expectedClassOrder = {
  target_mode: ["ON_TARGET", "CROSS_TARGET", "MARKET_GENERAL", "UNKNOWN"],
  stance: ["BULL", "BEAR", "NEUTRAL", "MIXED", "UNKNOWN"],
  emotion_primary: [
    "FEAR",
    "ANXIETY",
    "ANGER",
    "FRUSTRATION",
    "REGRET",
    "HOPE",
    "EXCITEMENT",
    "FOMO",
    "CALM",
    "NONE_EXPLICIT",
    "UNKNOWN",
  ],
  emotion_target: [
    "PRICE",
    "POSITION",
    "COMPANY",
    "MARKET",
    "OTHER",
    "NOT_APPLICABLE",
    "UNKNOWN",
  ],
  action_tendency: [
    "BUY",
    "ADD",
    "HOLD",
    "DO_T",
    "REDUCE",
    "SELL",
    "WATCH",
    "NO_ACTION_SIGNAL",
    "UNKNOWN",
  ],
  reasoning_tags: [
    "FUNDAMENTAL",
    "VALUATION",
    "TECHNICAL_PRICE",
    "FLOW_POSITIONING",
    "NEWS_EVENT",
    "RUMOR",
    "SOCIAL_PROOF",
    "MACRO_POLICY",
    "THEME_NARRATIVE",
    "NO_REASON_GIVEN",
    "RELATIVE_PERFORMANCE",
    "CROSS_STOCK_REFERENCE",
    "SARCASM_IRONY",
    "WORDPLAY",
    "UNKNOWN",
  ],
  context_dependency: [
    "SELF_CONTAINED",
    "PARTIAL_CONTEXT",
    "EXTERNAL_CONTEXT_REQUIRED",
    "UNKNOWN",
  ],
  label_confidence: ["HIGH", "MEDIUM", "LOW"],
};

const grouped = new Map();
for (const row of enumRows) {
  if (!grouped.has(row.field)) grouped.set(row.field, []);
  grouped.get(row.field).push({ label: row.label, definition: row.definition });
}
for (const [field, expected] of Object.entries(expectedClassOrder)) {
  const actual = (grouped.get(field) ?? []).map((entry) => entry.label);
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(
      `${field} class order mismatch: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`,
    );
  }
}
const unexpectedFields = [...grouped.keys()].filter(
  (field) => !(field in expectedClassOrder),
);
if (unexpectedFields.length) {
  throw new Error(`unexpected ENUM fields: ${unexpectedFields.join(", ")}`);
}

const v1HeadNames = [
  "target_mode",
  "stance",
  "emotion_primary",
  "emotion_target",
  "action_tendency",
  "reasoning_tags",
  "context_dependency",
];
const predictionHeads = Object.fromEntries(
  v1HeadNames.map((field) => [
    field,
    {
      task_type: field === "reasoning_tags" ? "multi_label" : "single_label",
      class_order: expectedClassOrder[field],
      classes: grouped.get(field),
    },
  ]),
);

const artifact = {
  artifact_schema_version: "myresearcher.semantic-label-schema.v1",
  schema_version: schemaVersion,
  status: "FROZEN",
  source: {
    original_workbook_path: inputPath,
    workbook_sha256: sourceSha256,
    sheet_name: sheetName,
    source_range: sourceRange,
    archived_date: archiveDate,
    export_script: "scripts/export_schema_from_workbook.mjs",
  },
  v1_prediction_heads: predictionHeads,
  audit_only_fields: {
    label_confidence: {
      purpose: "field-level sample weighting, filtering, and QA; not a prediction target",
      class_order: expectedClassOrder.label_confidence,
      classes: grouped.get("label_confidence"),
    },
    evidence_spans: {
      purpose: "training-data audit only; not generated by the V1 student",
    },
    ambiguity_note: {
      purpose: "training-data audit only; not generated by the V1 student",
    },
  },
  dependencies: dependencyRows,
};

await fs.mkdir(path.dirname(outputPath), { recursive: true });
await fs.writeFile(outputPath, `${JSON.stringify(artifact, null, 2)}\n`, "utf8");
